### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by mccxj** [mccxj/tidb#14]
- [x] error on large number with type bigint #4287
- [ ] tidb cannot support alter table comment #4990
- [ ] GUI client can't not show the rows of the table #3991
